In [1]:
import numpy as np 
np.set_printoptions(suppress=True)

In [2]:
loan_data= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_header=1,
                                          autostrip= True,
                                          )
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,
                nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,
                nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,
                nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,
                nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,
                nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,
                nan,      301.9 ]])

In [3]:
string_values= np.argwhere(np.isnan(np.nanmean(loan_data, axis = 0))).squeeze()
string_values

C:\Users\sasa_\AppData\Local\Temp\ipykernel_9800\2916383654.py:1: RuntimeWarning: Mean of empty slice
  string_values= np.argwhere(np.isnan(np.nanmean(loan_data, axis = 0))).squeeze()


array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [4]:
numeric_values= np.argwhere(np.isnan(np.nanmean(loan_data, axis = 0)) == False).squeeze()
numeric_values

C:\Users\sasa_\AppData\Local\Temp\ipykernel_9800\1310962089.py:1: RuntimeWarning: Mean of empty slice
  numeric_values= np.argwhere(np.isnan(np.nanmean(loan_data, axis = 0)) == False).squeeze()


array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [5]:
numeric_header= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_footer= loan_data.shape[0],
                                          autostrip= True,
                                          usecols= numeric_values,
                                          dtype= str)
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [6]:
loan_data_numeric= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_header=1,
                                          autostrip= True,
                                          usecols= numeric_values)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,
            9452.96],
       [57693261.  ,    30000.  ,    30000.  ,         nan,      938.57,
            4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,         nan,      494.86,
            1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,         nan,         nan,
            2185.64],
       [46154151.  ,         nan,    10000.  ,       16.55,      354.3 ,
            3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,         nan,      309.97,
             301.9 ]])

In [7]:
temporary_min= np.nanmin(loan_data_numeric, axis = 0).round(2)
temporary_mean= np.nanmean(loan_data_numeric, axis = 0).round(2)
temporary_max= np.nanmax(loan_data_numeric, axis = 0).round(2)
temporary_fill=np.nanmax(loan_data).round(2) + 1
temporary_stats= np.array([temporary_min,temporary_mean,temporary_max])

In [8]:
loan_data_numeric= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_header=1,
                                          autostrip= True,
                                          usecols= numeric_values,
                                          filling_values= temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,
            9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,
            4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,
            1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,
            2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,
            3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,
             301.9 ]])

In [9]:
numeric_header  # funded amount to the lowest and the rest to the highest 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [10]:
temporary_stats

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,
               0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,
            3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,
           41913.62]])

In [11]:
loan_data_numeric[:,2]= np.where(loan_data_numeric[:,2] == temporary_fill,
                                 temporary_stats[0][2],loan_data_numeric[:,2])

In [12]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [13]:
np.isnan(loan_data_numeric[:,2]).sum()

0

In [14]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i]= np.where(loan_data_numeric[:,i] == temporary_fill,
                                 temporary_stats[2][i],loan_data_numeric[:,i])

In [15]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,
            9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,
            4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,
            1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,
            2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,
            3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,
             301.9 ]])

In [16]:
np.isnan(loan_data_numeric).sum()

0

In [17]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [18]:
loan_data_numeric[:,3]= loan_data_numeric[:,3]/100 
loan_data_numeric[:,3]

array([0.1333, 0.2899, 0.2899, ..., 0.2899, 0.1655, 0.2899])

In [19]:
loan_data_numeric

array([[48010226.    ,    35000.    ,    35000.    ,        0.1333,
            1184.86  ,     9452.96  ],
       [57693261.    ,    30000.    ,    30000.    ,        0.2899,
             938.57  ,     4679.7   ],
       [59432726.    ,    15000.    ,    15000.    ,        0.2899,
             494.86  ,     1969.83  ],
       ...,
       [50415990.    ,    10000.    ,    10000.    ,        0.2899,
            1372.97  ,     2185.64  ],
       [46154151.    ,    35000.    ,    10000.    ,        0.1655,
             354.3   ,     3199.4   ],
       [66055249.    ,    10000.    ,    10000.    ,        0.2899,
             309.97  ,      301.9   ]])

In [20]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [21]:
EUR_USD= np.genfromtxt('EUR-USD.csv', delimiter= ',', dtype= str) # use close exchange rates
EUR_USD
                                      

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229',
        '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582',
        '1.1205360889434814', '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151',
        '1.0830246210098267', '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652',
        '1.1114321947097778', '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457',
        '1.0960345268249512', '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624',
        '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087',
        '1.0939244031906128', '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977',
        '1.1340054273605347', '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378',
   

In [22]:
EUR_USD= np.genfromtxt('EUR-USD.csv', delimiter= ',',
                                      skip_header= 1,
                                      usecols= 3) # use close exchange rates, for 12 months 
                                # ro7 ozbot awl column feh string_values b2a ro7 a3mlha lesa 34an tgeb 
                                # al months w mtrtben 
EUR_USD
                                      

array([1.1287955 , 1.12053609, 1.08302462, 1.11143219, 1.09603453,
       1.12229669, 1.0939244 , 1.13400543, 1.12559378, 1.10089719,
       1.05830181, 1.09339809])

In [23]:
loan_data_string= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_header=1,
                                          autostrip= True,
                                          usecols= string_values,
                                          dtype= str)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [24]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15',
       'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'],
      dtype='<U69')

In [25]:
loan_data_string[:,0]= np.chararray.strip(loan_data_string[:,0], '-15')
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May',
       'Nov', 'Oct', 'Sep'], dtype='<U69')

In [26]:
months= np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec'])

In [27]:
for i in range(13):
    loan_data_string[:,0]= np.where(loan_data_string[:,0] == months[i],
                                                             i,
                                                             loan_data_string[:,0])

In [28]:
loan_data_string[:,0].astype(np.int32)


array([ 5,  0,  9, ...,  6,  4, 12])

In [29]:
loan_data_string[:,0]  # 34an dtype = str fha yfdl y5leha str f lazm t2lb kol al columns numeric
                       # w b3deha 5le al data type int 32,64

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [30]:
np.unique(loan_data_string[:,0]) 

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'],
      dtype='<U69')

In [31]:
exchange_rate = loan_data_string[:,0].astype(np.int32)
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [32]:
exchange_rate.size

10000

In [33]:
EUR_USD

array([1.1287955 , 1.12053609, 1.08302462, 1.11143219, 1.09603453,
       1.12229669, 1.0939244 , 1.13400543, 1.12559378, 1.10089719,
       1.05830181, 1.09339809])

In [34]:
for i in range(1,13):  # al zero m4 3awzo 34an kan ''  asasn
    exchange_rate= np.where(exchange_rate == i, EUR_USD[i-1], exchange_rate)

In [35]:
exchange_rate= exchange_rate.round(2)
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [36]:
exchange_rate.shape

(10000,)

In [37]:
loan_data_numeric= np.hstack((loan_data_numeric, np.reshape(exchange_rate,(10000,1))))

In [38]:
loan_data_numeric.shape  # 3mlt stack lel exchange rate 

(10000, 7)

In [39]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [40]:
numeric_header =np.concatenate((numeric_header, np.array(['exchange_rate'])))
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt', 'exchange_rate'], dtype='<U13')

In [41]:
in_dollars =np.array([1,2,4,5])

In [42]:
loan_data_numeric[:,6]

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [43]:
for i in in_dollars:
    loan_data_numeric= np.hstack((loan_data_numeric,
                                  np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

C:\Users\sasa_\AppData\Local\Temp\ipykernel_9800\2130001492.py:3: RuntimeWarning: divide by zero encountered in true_divide
  np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))
C:\Users\sasa_\AppData\Local\Temp\ipykernel_9800\2130001492.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))


In [44]:
loan_data_numeric.shape   # kano 6 + exchange rate +  [1,2,4,5] al godad b2o 11 keda

(10000, 11)

In [45]:
additional_headers= np.array([column_name + '_EUR' for column_name in numeric_header[in_dollars]])
additional_headers  # tre2a 7lwa a7fzha 

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U15')

In [46]:
numeric_header= np.concatenate((numeric_header, additional_headers))
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR',
       'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [47]:
numeric_header.shape

(11,)

In [48]:
numeric_header[in_dollars]= np.array([column_name + '_USD' for column_name in numeric_header[in_dollars]])
numeric_header  # tre2a 7lwa a7fzha 

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate',
       'installment_USD', 'total_pymnt_USD', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U15')

In [49]:
string_header= np.genfromtxt('loan-data.csv', delimiter= ';',
                                          skip_footer= loan_data.shape[0],
                                          autostrip= True,
                                          usecols= string_values,
                                          dtype= str)
string_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [50]:
loan_data_string

array([['5', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['0', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['9', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['6', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['4', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['12', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [51]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid',
       'In Grace Period', 'Issued', 'Late (16-30 days)',
       'Late (31-120 days)'], dtype='<U69')

In [52]:
bad_status= np.array(['', 'Charged Off','Default','Late (31-120 days)'])
bad_status

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [53]:
loan_data_string[:,1]= np.where(np.isin(loan_data_string[:,1], bad_status),0,1 )
loan_data_string[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [54]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [55]:
loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months',
       '36 months', '36 months'], dtype='<U69')

In [56]:
loan_data_string[:,2] =np.chararray.strip(loan_data_string[:,2],' months')
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [57]:
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [58]:
loan_data_string[:,2]= np.where(loan_data_string[:,2] == '', 0, loan_data_string[:,2] )
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [59]:
np.unique(loan_data_string[:,2])

array(['0', '36', '60'], dtype='<U69')

In [60]:
string_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [61]:
loan_data_string[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [62]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [63]:
np.unique(loan_data_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5',
        'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1',
        'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
        'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567,
        586, 564, 423, 391, 267, 250, 255, 223, 235, 162, 171, 139, 114,
         94,  52,  34,  43,  16,  19,  10,   3,   7,   2], dtype=int64))

In [64]:
np.unique(loan_data_string[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [65]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4]= np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                     i + '5', loan_data_string[:,4] )

In [66]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5',
        'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1',
        'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
        'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567,
        586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,
         94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [67]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4]= np.where((loan_data_string[:,4] == ''),
                                     'H1', loan_data_string[:,4] )

In [68]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1',
        'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2',
        'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3',
        'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586,
        564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,
         52,  34,  43,  24,  19,  10,   3,   7,   5,   9], dtype=int64))

In [69]:
np.unique(loan_data_string[:,4]).size

36

In [70]:
keys= list(np.unique(loan_data_string[:,4]))
values= list(range(1,37))
dic= dict(zip(keys,values))
dic

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [71]:
for i in np.unique(loan_data_string[:,4]): # mmkn t5leha be 0 brdo
    loan_data_string[:,4]= np.where(loan_data_string[:,4] == i, dic[i], loan_data_string[:,4] )

In [72]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
        '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
        '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6', '7',
        '8', '9'], dtype='<U69'),
 array([285, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 278, 288,
        235, 162, 171, 139, 160,  94,  52,  34,  43, 239,  24,  19,  10,
          3,   7,   5,   9, 323, 592, 509, 517, 530, 553], dtype=int64))

In [73]:
string_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [74]:
string_header= np.delete(string_header,3)

In [75]:
loan_data_string= np.delete(loan_data_string,3, axis = 1)

In [76]:
string_header[2]= 'term_months'
string_header

array(['issue_d', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [77]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [78]:
bad_status= np.array(['', 'Not Verified',])

In [79]:
loan_data_string[:,4]= np.where(np.isin(loan_data_string[:,4],bad_status),0,1)

In [80]:
loan_data_string[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [81]:
np.unique(loan_data_string[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426',
       ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'],
      dtype='<U69')

In [82]:
loan_data_string[:,5]= np.chararray.strip(loan_data_string[:,5] ,"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [83]:
loan_data_string[:,5].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [84]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151.,
       66055249.])

In [85]:
np.array_equal(loan_data_string[:,5].astype(np.int32),loan_data_numeric[:,0])

True

In [86]:
loan_data_string= np.delete(loan_data_string,5, axis = 1)
string_header= np.delete(string_header, 5)

In [87]:
string_header

array(['issue_d', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'addr_state'], dtype='<U19')

In [88]:
string_header[0]= 'issue_date'
string_header[5]= 'state_address'
string_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

In [89]:
np.unique(loan_data_string[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL',
        'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI',
        'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV',
        'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT',
        'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,
         321,   44,  389,  152,   84,   84,  116,  210,  222,   10,  267,
         156,  160,   61,   28,  261,   16,   25,   58,  341,   57,  130,
         777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,
         242,   17,  216,  148,   49,   27], dtype=int64))

In [90]:
loan_data_string[:,5]= np.where(loan_data_string[:,5] == '' ,0, loan_data_string[:,5])

In [91]:
state_west= np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
state_south= np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
state_midwest= np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
state_east= np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [92]:
loan_data_string[:,5]= np.where(np.isin(loan_data_string[:,5], state_west), 1, loan_data_string[:,5])
loan_data_string[:,5]= np.where(np.isin(loan_data_string[:,5], state_south), 2, loan_data_string[:,5])
loan_data_string[:,5]= np.where(np.isin(loan_data_string[:,5], state_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5]= np.where(np.isin(loan_data_string[:,5], state_east), 4, loan_data_string[:,5])

In [93]:
np.unique(loan_data_string[:,5], return_counts = True)

(array(['0', '1', '2', '3', '4'], dtype='<U69'),
 array([ 500, 2467, 3384, 1733, 1916], dtype=int64))

In [94]:
string_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

In [95]:
loan_data_string =loan_data_string.astype(np.int32)
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [96]:
numeric_header

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate',
       'installment_USD', 'total_pymnt_USD', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U15')

In [97]:
loan_data_numeric =loan_data_numeric.round(2)

In [98]:
loan_data.shape

(10000, 14)

In [99]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31818.18,
            1077.15,     8593.6 ],
       [57693261.  ,    30000.  ,    30000.  , ...,         inf,
                inf,         inf],
       [59432726.  ,    15000.  ,    15000.  , ...,    13274.34,
             437.93,     1743.21],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8928.57,
            1225.87,     1951.46],
       [46154151.  ,    35000.  ,    10000.  , ...,     9009.01,
             319.19,     2882.34],
       [66055249.  ,    10000.  ,    10000.  , ...,     9174.31,
             284.38,      276.97]])

In [100]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [101]:
loan_data= np.hstack((loan_data_numeric,loan_data_string))

In [102]:
loan_data

array([[48010226.,    35000.,    35000., ...,       13.,        1.,
               1.],
       [57693261.,    30000.,    30000., ...,        5.,        1.,
               4.],
       [59432726.,    15000.,    15000., ...,       10.,        1.,
               4.],
       ...,
       [50415990.,    10000.,    10000., ...,        5.,        1.,
               1.],
       [46154151.,    35000.,    10000., ...,       17.,        1.,
               3.],
       [66055249.,    10000.,    10000., ...,        4.,        0.,
               3.]])

In [103]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [104]:
loan_data =loan_data[np.argsort(loan_data[:,0])]

In [105]:
loan_data

array([[  373332.,     9950.,     1000., ...,       21.,        0.,
               1.],
       [  575239.,    12000.,    12000., ...,       25.,        1.,
               2.],
       [  707689.,    10000.,    10000., ...,       13.,        1.,
               0.],
       ...,
       [68614880.,     5600.,     5600., ...,        8.,        1.,
               1.],
       [68615915.,     4000.,     4000., ...,       10.,        1.,
               2.],
       [68616519.,    21600.,    21600., ...,        3.,        0.,
               2.]])

In [106]:
full_header =np.concatenate((numeric_header,string_header))

In [107]:
full_header

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate',
       'installment_USD', 'total_pymnt_USD', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR', 'issue_date', 'loan_status', 'term_months',
       'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [108]:
loan_data =np.vstack((full_header,loan_data))

In [109]:
loan_data

array([['id', 'loan_amnt_USD', 'funded_amnt_USD', ..., 'sub_grade',
        'verification_status', 'state_address'],
       ['373332.0', '9950.0', '1000.0', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '12000.0', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5600.0', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '4000.0', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '21600.0', ..., '3.0', '0.0', '2.0']],
      dtype='<U32')

In [110]:
np.savetxt('loan-data-preprocessed', loan_data, fmt= '%s' ,delimiter= ',' )

In [111]:
np.genfromtxt('loan-data-preprocessed', delimiter = ',', autostrip = True, skip_header = 1 )

array([[  373332.,     9950.,     1000., ...,       21.,        0.,
               1.],
       [  575239.,    12000.,    12000., ...,       25.,        1.,
               2.],
       [  707689.,    10000.,    10000., ...,       13.,        1.,
               0.],
       ...,
       [68614880.,     5600.,     5600., ...,        8.,        1.,
               1.],
       [68615915.,     4000.,     4000., ...,       10.,        1.,
               2.],
       [68616519.,    21600.,    21600., ...,        3.,        0.,
               2.]])

In [112]:
# zyada

In [113]:
for i in np.argwhere(np.isnan(Numeric_values_NAN)):  # a7la filling lel values 
    Numeric_values_NAN[i[0],i[1]] = 0
Numeric_values_NAN

NameError: name 'Numeric_values_NAN' is not defined